spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: mall
#        namespace: 3ed108bd-a058-434b-858a-5fc4db30e4ce
        namespace: a6f95764-e0b0-43f3-8df9-0ddfc53b31fb
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Method=GET,POST
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Method=GET,POST
            - Path=/admin/**
          filters:
            - StripPrefix=1

security:
  oauth2:
    client:
      client-id: admin-app
      client-secret: secret
      access-token-uri: http://localhost:8092/oauth/token
      user-authorization-uri: http://localhost:8092/oauth/authorize
    resource:
      token-info-uri: http://localhost:8092/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9081