spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.68.225:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Method=GET,POST
            - Path=/auth/**

        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Method=GET,POST
            - Path=/admin/**

        - id: mall-portal
          uri: lb://mall-portal
          predicates:
            - Method=GET,POST
            - Path=/portal/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9082/rsa/publicKey' #配置RSA的公钥访问地址

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8888

security:
  ignore:
    urls:
      - "/oauth/login"
      - "/v2/api-docs/**"
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"