spring:
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.68.225:8848
  redis:
    host: 59.110.68.225
    port: 6379
    lettuce:
      pool:
        max-idle: 8

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9082

#logging:
#  level:
#    root: debug
