spring:
  application:
    name: mall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.68.225:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.68.225:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: 721000
    type: com.zaxxer.hikari.HikariDataSource

  redis:
    host: 59.110.68.225
    port: 6379
    password: ZS123456qwertyuiop
    lettuce:
      pool:
        max-idle: 8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tang.mall.common
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志
    map-underscore-to-camel-case: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9082

#logging:
#  level:
#    root: debug
