spring:
  application:
    name: mall-portal
  cloud:
    nacos:
      discovery:
        server-addr: 59.110.68.225:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://59.110.68.225:3306/mall?serverTimezone=GMT%2B8
    username: root
    password: 721000
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 59.110.68.225
    lettuce:
      pool:
        max-idle: 8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tang.mall.common
  #  config-location: classpath:mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 日志
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9083



